const titles = [
  // main titles for each unit
  [
    "",
    "",
    "Economia i Emprenedoria. Programació i UD2",
    "Economia i Emprenedoria. Programació i UD3",
    "Economia i Emprenedoria. Programació i UD4",
    "Economia i Emprenedoria. Programació i UD5",
    "Economia i Emprenedoria. Programació i UD6",
    "Economia i Emprenedoria. Programació i UDC1",
    "Economia i Emprenedoria. Programació i UDC2"
  ],
  [],
  // ud2
  [
    "Presentació de la programació i UD2",
    "General_Activitats_Avaluació_UD2",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S01_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S02_Kanban board_A3",
    "S03_Què és un pressupost_Activitats",
    "S03_Sac de dubtes",
    "S04_Renda disponible_Activitats",
    "S05_Destí renda disponible_Activitats",
    "S06_Repàs full càlcul_Activitats",
    "S07_Fem el pressupost_Full càlcul",
    "S08_Productes consum_alternatives_Activitats",
    "S08_Bastida suport_consum responsable",
    "S09_Consum responsable_alternatives_Activitats",
    "S09_Font 1_Consum conscient",
    "S09_Font 2_Presa decisions",
    "S09_Font 3_Principis consum responsable",
    "S10_Comerç just_Experts",
    "S10_Píndola formativa_comerç just",
    "S10_Comerç just_Còmic",
    "S12_Bretxa salarial_Dinàmica",
    "S12_Font consulta extra_Dossier 8M_2019",
    "S12_Font consulta extra_Llei 17/2015",
    "S13_Estalvi i entitats bancàries",
    "S14_Finançament_Activitats",
    "S14_Píndola formativa_Finançament_Entitats Bancàries",
    "S14_Píndola formativa_Alternatives finançament",
    "S14_Bastida de suport_Notes",
    "S15_Bastida de suport_Mapa mut",
    "S16_Rúbrica presentació",
    "S17_Metacognició",
    "S17_Rúbrica producte_UD2"
  ],
  // ud3
  [
    "Presentació de la programació i UD3",
    "General_Activitats_Avaluació_UD3",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S02_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S03_Píndola formativa_Empresa",
    "S03_Font consulta còmic_Empresa",
    "S03_Font consulta còmic_Enterprise",
    "S03_Sac de dubtes",
    "S04_Píndola formativa_ADN Empresa",
    "S04_RSC_Activitats_Taula i qüestions",
    "S04_Font lectura_Nespresso_Greenwashing",
    "S04_Font lectura_Socialwashing_Greenwashing",
    "S04_Font lectura_RSC_Treballar fins a defallir",
    "S05_Píndola formativa_Empresa i entorn",
    "S05_Font consulta_Manifest Cluetrain",
    "S05_Bastida de suport_Mapa mut_Empresa",
    "S06_Píndola formativa_Tipus empresa",
    "S06_Píndola formativa_Aproximació_MovCooperatiu",
    "S06_Font consulta extra_Capacitats_Cooperatives",
    "S06_Bastida de suport_Presa notes",
    "S07_Competir cooperant_CCMA",
    "S08_Píndola formativa_Funcions_Treball equip",
    "S09_Empresa i dona_Lideratge femení",
    "S09_Font 1_Lideratge femení i valors",
    "S09_Font 2_Dones_Consells d’Administració",
    "S09_Font consulta extra_Dosseier 8M_2019 ",
    "S09_Font consulta extra_Llei 17/2015 ",
    "S10_Píndola formativa_I_C_PM",
    "S11_Fiscalitat i empresa",
    "S11_Font lectura_Impostos_Amazon_Parada salsitxes",
    "S11_Font consulta extra_Fiscalitat ambiental",
    "S12_ABJ_Cas 1_Entrenament_Viure plegats_models cooperatius",
    "S12_ABJ_Cas 2_Abacus_Joguines responsables",
    "S12_ABJ_Cas 2_Fiscalitat justa",
    "S12_ABJ_Cas 2_Adaptació entorn dinàmic",
    "S15_Rúbrica_ABJ_UD3",
    "S15_Rúbrica_actitud_UD3",
    "S15_Rúbrica_mapa XL_UD3",
    "S15_Metacognició"
  ],
  // ud4
  [
    "Presentació de la programació i UD4",
    "General_Activitats_Avaluació_UD4",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S02_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S03_Activitat i síntesi_SP",
    "S04_Activitat ingressos",
    "S05_Impostos_D_I_Exercitació",
    "S06_Anàlisi dades_Despesa_Activitat",
    "S06_Rúbrica equip",
    "S07_Anàlisi Despesa",
    "S08_Bastida suport_presa notes",
    "S08_Resultat econòmic SP_Activitat",
    "S09_Font 1_Vicenç Navarro",
    "S09_Font 2_Economies_extractives_inclusives",
    "S09_Control dèficit_Ingressos",
    "S10_Estat Benestar_Experts",
    "S10_Síntesi EB_Visual Thinking",
    "S10_Plans equip",
    "S11_Valors_EB",
    "S12_Gènere_SP_Activitats",
    "S12_Font 1_Lideratge femení i valors",
    "S12_Font 2_Mapa_Women in polítics",
    "S12_Font consulta extra_Dossier 8M_2019",
    "S12_Font consulta extra_Llei 17/2015",
    "S14_Revisió_Plans equip",
    "S14_Bastida suport_mapa mut",
    "S15_Rúbrica_Presentació",
    "S17_Rúbrica_actitud_UD4",
    "S17_Rúbrica_equip_UD4",
    "S17_Metacognició"
  ],
  // ud5
  [
    "Presentació de la programació i UD5",
    "General_Activitats_Avaluació_UD5",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S01_Activitat motivació",
    "S01_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S03_Economia_cicles_PIB",
    "S04_Activitat_comentari PIB",
    "S04_Font consulta_Informe_Treball domèstic",
    "S04_Font consulta_Informe_ODEE",
    "S04_Font consulta extra_Llei 17/2015",
    "S04_Font consulta_Oxfam",
    "S05_Píndola formativa_atur_Experts",
    "S05_Font consulta_Informe Dones a Catalunya_2020",
    "S05_Bastida suport_mapa atur",
    "S05_Font consulta_Efectes_Precarietat laboral",
    "S05_Font consulta_Atur i dona",
    "S06_Anàlisi dades_Atur",
    "S08_Font consulta_Còmic_Inflació",
    "S08_Anàlisi dades_Inflació",
    "S09_Bastida suport_presa notes",
    "S10_Activitat reflexió",
    "S10_Font consulta_Vicenç Navarro_pobresa",
    "S11_Infografies",
    "S12_Rúbrica_Producte",
    "S12_Rúbrica_Actualització EPA",
    "S12_Rúbrica_Actitud",
    "S12_Rúbrica_Equip_voluntària",
    "S12_Metacognició"
  ],
  // ud6
  [
    "Presentació de la programació i UD6",
    "General_Activitats_Avaluació_UD6",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S01_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S02_Plans equip",
    "S03_Aproximació CI",
    "S03_Estructura 1-2-4 CI",
    "S03_Mapa mut_CI",
    "S03_Bastida suport_Mapa mut_CI",
    "S04_Beneficis CI",
    "S05_Globalització",
    "S05_Visual Thinking_Globablització",
    "S05_Bastida suport_Presa notes",
    "S06_Ens qüestionem_DH",
    "S06_Revisió_Plans equip",
    "S06_Mapa mut_DH",
    "S07_Indicadors alternatius_Experts",
    "S07_Font_Per saber-ne més",
    "S08_Indicadors_PIB_IDH",
    "S08_Font consulta 2018_IDH",
    "S09_Dinàmica cubs_CI",
    "S10_Eixos opressió_Activitat",
    "S10_Font consulta_grup C i D",
    "S10_Avaluació_Plans equip",
    "S10_Rúbrica_Plans equip",
    "S14_Globalització_Àmbit",
    "S16_Acció comunicació",
    "S16_Lectura voluntària",
    "S18_Rúbrica_Mapa_D.Ishikawa",
    "S18_Rúbrica_Actitud",
    "S18_Metacognició"

  ],
  // udc1
  [
    "Presentació de la programació i UDC1",
    "General_Activitats_Avaluació_UDC1",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S02_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S03_Píndola formativa_EPA",
    "S03_Exemple_Creative common",
    "S04_Autoconeixement_VThinking",
    "S04_Proposta_Activitats",
    "S05_IDigital_EduCAC",
    "S05_EPA_Organitzador continguts_Wakelet",
    "S06_Mapa educatiu",
    "S07_Biaix_Gènere i estudis_Experts",
    "S07_Font_Dones FP",
    "S07_Font_Biaix HD_Universitat",
    "S07_Font addicional_Dona_Mercat laboral",
    "S08_4a Revolució Industrial_Experts",
    "S08_Bastida suport_Presa notes",
    "S08_Font_Empleat AAA_Grup D",
    "S08_Font_4a revolució_Grup B",
    "S10_S11_Producció_Portafolis",
    "S12_Rúbrica_Presentació",
    "S13_Rúbrica_EPA",
    "S13_Rúbrica_Actitud",
    "S13_Metacognició",
  ],
  // udc2
  [
    "Presentació de la programació i UDC2",
    "General_Activitats_Avaluació_UDC2",
    "General_Font lectura extra_Còmic",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S01_Activitat motivació",
    "S01_Flipped classroom_valors emprenedors",
    "S02_Creativitat_Emprenedoria_Experts_Síntesi",
    "S02_Font_addicional_Dona i publicitat",
    "S05_Barreres_creativitat_Activitat",
    "S06_Observació",
    "S07_Brain storming invers_Ideació",
    "S08_Combinació",
    "S09_Resiliència",
    "S10_Comuniquem_cor_ment",
    "S12_Break out_Reflexió activitats",
    "S12_Think outside the box",
    "S12_Rúbrica_Actitud",
    "S12_Rúbrica_Actualització EPA",
    "S12_Conte",
    "S12_Metacognició"
  ],
];

const footers = [
  "",
  "",
  // ud2
  "<p class='footer'>Nota: Per elaborar aquesta unitat s’han utilitzat propostes de treball i materials del:<br>- Llibret d’educació financera a l’ESO editat pel Ministerio de Educación.<br>- Mòduls formatius 2, 4 i 5 d’economia social i finances ètiques d’Economia Social Catalunya.<br>- Llibre de text: Economia i emprenedoria 4t ESO de l’editorial Barcanova.</p>",
  // ud3
  "<p class='footer'>Nota: Aquesta unitat està inspirada en el Word Peace Game i s’han utilitzat propostes de treball del:<br>- Mòdul formatiu d’economia social i finances ètiques d’Economia Social Catalunya.<br>- Llibre de text: Economia i emprenedoria 4t ESO de l’editorial Barcanova.</p>",
  // ud4
  "<p class='footer'>Nota: Per elaborar aquesta unitat s’han utilitzat propostes de treball i materials de:<br>- Materials educatius EduCaixa.<br>- Llibre de text: Economia i emprenedoria 4t ESO de l’editorial Barcanova.</p>",
  // ud5
  "",
  // ud6
  "",
  // udc1
  "",
  // udc2
  "<p class='footer'>Nota: Per elaborar aquesta unitat s’han utilitzat algunes tècniques per entrenar i avaluar la creativitat proposades en el llibre Crear i fer ampolles. Eines per educar la creativitat. Maria Batet, Franc Ponti i Enric Segarra.</p>"
];