const titles = [
  // main titles for each unit
  [
    "",
    "",
    "Economia i Emprenedoria. Programació i UD2"
  ],
  [],
  // ud2
  ["Presentació de la programació i UD2",
    "General_Activitats_Avaluació_UD2",
    "S01_Presentació objectius_CA_IA",
    "S01_Coneixements previs",
    "S01_Activitat motivació",
    "S02_Preguntes abans del procés",
    "S02_Pla_Treball_A3",
    "S02_Kanban board_A3",
    "S03_Què és un pressupost_Activitats",
    "S03_Sac de dubtes",
    "S04_Renda disponible_Activitats",
    "S05_Destí renda disponible_Activitats",
    "S06_Repàs full càlcul_Activitats",
    "S07_Fem el pressupost_Full càlcul",
    "S08_Productes consum_alternatives_Activitats",
    "S08_Bastida suport_consum responsable",
    "S09_Consum responsable_alternatives_Activitats",
    "S09_Font 1_Consum conscient",
    "S09_Font 2_Presa decisions",
    "S09_Font 3_Principis consum responsable",
    "S10_Comerç just_Experts",
    "S10_Píndola formativa_comerç just",
    "S10_Comerç just_Còmic",
    "S12_Bretxa salarial_Dinàmica",
    "S12_Font consulta extra_Dossier 8M_2019",
    "S12_Font consulta extra_Llei 17/2015",
    "S13_Estalvi i entitats bancàries",
    "S14_Finançament_Activitats",
    "S14_Píndola formativa_Finançament_Entitats Bancàries",
    "S14_Píndola formativa_Alternatives finançament",
    "S14_Bastida de suport_Notes",
    "S15_Bastida de suport_Mapa mut",
    "S16_Rúbrica presentació",
    "S17_Metacognició",
    "S17_Rúbrica producte_UD2"
  ],
];